apiVersion: v1
kind: Service
metadata:
  name: angular-hello-svc
  namespace: app-at2
  labels:
    app: angular-hello
spec:
  selector:
    app: angular-hello
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4200
      name: http