apiVersion: v1
kind: Service
metadata:
  name: springboot-hello-svc
  namespace: app-at2
  labels:
    app: springboot-hello
spec:
  selector:
    app: springboot-hello
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http